markdown: kramdown
highlighter: pygments
permalink: :year/:month/:day/:title
relative_permalinks: true
rdiscount:
  extensions: [smart]
title : Isabelle M
production_url : http://isabellema.free.fr/dev/blog
description: "Blabla by Isabelle Mahnich."
disqus_shortname: isabellema
author :
  name : Isabelle M
  github : isabellema
