markdown: kramdown
highlighter: rouge
permalink: :year/:month/:day/:title
baseurl: /dev/blog
production_url : http://isabellema.free.fr/dev/blog/
title : Isabelle M
description: "Blabla by Isabelle Mahnich."
author :
  name : Isabelle M
  github : isabellema
